#生产环境配置

server:
  port: 7000
  servlet:
    context-path: /mistore

spring:
  resources:
    cache:
      cachecontrol:
        max-age: 3600
    chain:
      cache: true
      enabled: true
      compressed: true   #启用压缩资源解析

  datasource:
    url: jdbc:mysql://47.98.145.198:3306/mistore?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useAffectedRows=true
    username: aliyun
    password: liuxianchun
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 47.98.145.198
    port: 6379
    timeout: 1000
    database: 0
    lettuce:
      pool:
        max-active: 15
        max-wait: 5000ms
        max-idle: 10
    password: liuxianchun

  mvc:
    hiddenmethod:
      filter:
        enabled: true  #启用表单REST风格
    contentnegotiation:
      favor-parameter: true  #开启请求参数内容协商